import type { RouteRecordRaw } from 'vue-router'

export const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/login/index.vue'),
    meta: { title: '登录' },
  },
  {
    path: '/register',
    name: 'Register',
    component: () => import('@/views/auth/RegisterPage.vue'),
    meta: { title: '注册' },
  },
  {
    path: '/forgot-password',
    name: 'ForgotPassword',
    component: () => import('@/views/auth/ForgotPasswordPage.vue'),
    meta: { title: '找回密码' },
  },
  {
    path: '/',
    component: () => import('@/layouts/DefaultLayout.vue'),
    redirect: '/dashboard',
    children: [
      {
        path: 'dashboard',
        name: 'Dashboard',
        component: () => import('@/views/home/index.vue'),
        meta: { title: '仪表盘', icon: 'Odometer' },
      },
      {
        path: 'requirements',
        name: 'Requirements',
        component: () => import('@/views/requirements/index.vue'),
        meta: { title: '需求管理', icon: 'Document' },
      },
      {
        path: 'requirements/:id',
        name: 'RequirementDetail',
        component: () => import('@/views/requirements/detail.vue'),
        meta: { title: '需求详情', hidden: true },
      },
      {
        path: 'requirements/create',
        name: 'RequirementCreate',
        component: () => import('@/views/requirements/create.vue'),
        meta: { title: '新建/编辑需求', hidden: true },
      },
      {
        path: 'iterations',
        name: 'Iterations',
        component: () => import('@/views/iterations/index.vue'),
        meta: { title: '迭代管理', icon: 'Calendar' },
      },
      {
        path: 'reviews',
        name: 'Reviews',
        component: () => import('@/views/reviews/index.vue'),
        meta: { title: '评审管理', icon: 'ChatDotRound', hidden: true },
      },
      {
        path: 'statistics',
        name: 'Statistics',
        component: () => import('@/views/statistics/index.vue'),
        meta: { title: '统计报表', icon: 'TrendCharts' },
      },
      {
        path: 'settings/rag',
        name: 'RagCenter',
        component: () => import('@/views/rag/index.vue'),
        meta: { title: 'RAG文档中心', icon: 'Files', requiredPermissions: ['menu:rag'] },
      },
      {
        path: 'settings/knowledge',
        name: 'KnowledgeBases',
        component: () => import('@/views/knowledge/index.vue'),
        meta: { title: '知识库管理', icon: 'Collection', requiredPermissions: ['menu:rag'] },
      },
      {
        path: 'settings/knowledge/:id',
        name: 'KnowledgeDetail',
        component: () => import('@/views/knowledge/detail.vue'),
        meta: { title: '知识库详情', hidden: true, requiredPermissions: ['menu:rag'] },
      },
      {
        path: 'settings/knowledge/search',
        name: 'KnowledgeSearch',
        component: () => import('@/views/knowledge/search.vue'),
        meta: { title: '全局语义检索', hidden: true, requiredPermissions: ['menu:rag'] },
      },
      {
        path: 'settings',
        name: 'Settings',
        component: () => import('@/views/settings/index.vue'),
        meta: { title: '系统配置', icon: 'Setting', requiredPermissions: ['menu:system-config'] },
      },
      {
        path: 'settings/projects',
        name: 'ProjectSettings',
        component: () => import('@/views/settings/projects.vue'),
        meta: { title: '项目管理', hidden: true, requiredPermissions: ['menu:settings:project'] },
      },
      {
        path: 'settings/users',
        name: 'UserManage',
        component: () => import('@/views/settings/users.vue'),
        meta: { title: '用户管理', hidden: true, requiredPermissions: ['menu:settings:user'] },
      },
      {
        path: 'settings/org',
        name: 'OrgManage',
        component: () => import('@/views/settings/org.vue'),
        meta: { title: '组织架构', hidden: true, requiredPermissions: ['menu:settings:org'] },
      },
      {
        path: 'system/organization',
        name: 'OrganizationManagement',
        component: () => import('@/views/system/organization/index.vue'),
        meta: { title: '组织架构管理', icon: 'OfficeBuilding' },
      },
      {
        path: 'system/workflow-config',
        name: 'WorkflowConfig',
        component: () => import('@/views/system/workflow-config/index.vue'),
        meta: { title: '工作流配置', icon: 'Share', requiredRoles: ['admin', 'workflow:config'], requiredPermissions: ['menu:settings:workflow'] },
      },
      {
        path: 'system/workflow-config/editor',
        name: 'WorkflowConfigEditor',
        component: () => import('@/views/system/workflow-config/editor.vue'),
        meta: { title: '工作流编辑器', hidden: true },
      },
      {
        path: 'settings/requirements',
        name: 'RequirementConfig',
        component: () => import('@/views/settings/requirements.vue'),
        meta: { title: '需求配置', hidden: true, requiredPermissions: ['menu:settings:requirement'] },
      },
      {
        path: 'settings/menus',
        name: 'MenuManagement',
        component: () => import('@/views/settings/menus.vue'),
        meta: { title: '菜单管理', hidden: true, requiredPermissions: ['menu:menu-management'] },
      },
      {
        path: 'settings/llm',
        name: 'LlmConfig',
        component: () => import('@/views/settings/llm.vue'),
        meta: { title: '模型配置', hidden: true, requiredPermissions: ['menu:settings:llm'] },
      },
      {
        path: 'notifications',
        name: 'Notifications',
        component: () => import('@/views/notifications/index.vue'),
        meta: { title: '通知中心', hidden: true },
      },
    ],
  },
]
