import type { RouteRecordRaw } from 'vue-router'

export const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/login/index.vue'),
    meta: { title: '登录' },
  },
  {
    path: '/register',
    name: 'Register',
    component: () => import('@/views/auth/RegisterPage.vue'),
    meta: { title: '注册' },
  },
  {
    path: '/forgot-password',
    name: 'ForgotPassword',
    component: () => import('@/views/auth/ForgotPasswordPage.vue'),
    meta: { title: '找回密码' },
  },
  {
    path: '/public/share/:token',
    name: 'KnowledgePublicShare',
    component: () => import('@/views/public/KnowledgeSharePage.vue'),
    meta: { title: '文档分享', publicAccess: true },
  },
  {
    path: '/public/bitable/form/:token',
    name: 'BitablePublicForm',
    component: () => import('@/views/public/PublicFormPage.vue'),
    meta: { title: '表单填写', publicAccess: true },
  },
  {
    path: '/public/bitable/view/:token',
    name: 'BitablePublicView',
    component: () => import('@/views/public/PublicShareViewPage.vue'),
    meta: { title: '数据视图', publicAccess: true },
  },
  {
    path: '/public/invite/:code',
    name: 'InviteAccept',
    component: () => import('@/views/public/InviteAcceptPage.vue'),
    meta: { title: '接受邀请', publicAccess: true },
  },
  {
    path: '/',
    component: () => import('@/layouts/DefaultLayout.vue'),
    redirect: '/dashboard',
    children: [
      {
        path: 'dashboard',
        name: 'Dashboard',
        component: () => import('@/views/home/index.vue'),
        meta: { title: '仪表盘', icon: 'Odometer' },
      },
      {
        path: 'requirements',
        name: 'Requirements',
        component: () => import('@/views/requirements/index.vue'),
        meta: { title: '需求管理', icon: 'Document' },
      },
      {
        path: 'requirements/:id',
        name: 'RequirementDetail',
        component: () => import('@/views/requirements/detail.vue'),
        meta: { title: '需求详情', hidden: true, activeMenu: '/requirements' },
      },
      {
        path: 'requirements/create',
        name: 'RequirementCreate',
        component: () => import('@/views/requirements/create.vue'),
        meta: { title: '新建/编辑需求', hidden: true, activeMenu: '/requirements' },
      },
      {
        path: 'iterations',
        name: 'Iterations',
        component: () => import('@/views/iterations/index.vue'),
        meta: { title: '迭代管理', icon: 'Calendar' },
      },
      {
        path: 'bitable',
        name: 'BitableList',
        component: () => import('@/views/bitable/index.vue'),
        meta: { title: '多维表格', icon: 'Grid' },
      },
      {
        path: 'bitable/:baseId',
        name: 'BitableEditor',
        component: () => import('@/views/bitable/editor.vue'),
        meta: { title: '多维表格编辑', hidden: true, activeMenu: '/bitable' },
      },
      {
        path: 'bitable/:baseId/dashboard',
        name: 'BitableDashboard',
        component: () => import('@/views/bitable/dashboard.vue'),
        meta: { title: '多维表格仪表盘', hidden: true, activeMenu: '/bitable' },
      },
      {
        path: 'settings/knowledge',
        name: 'KnowledgeBases',
        component: () => import('@/views/knowledge/index.vue'),
        meta: { title: '知识库管理', icon: 'Collection', requiredPermissions: ['menu:knowledge'] },
      },
      {
        path: 'settings/knowledge/:id',
        name: 'KnowledgeDetail',
        component: () => import('@/views/knowledge/detail.vue'),
        meta: { title: '知识库详情', hidden: true, activeMenu: '/settings/knowledge', requiredPermissions: ['menu:knowledge'] },
      },
      {
        path: 'settings/knowledge/search',
        name: 'KnowledgeSearch',
        component: () => import('@/views/knowledge/search.vue'),
        meta: { title: '全局语义检索', hidden: true, activeMenu: '/settings/knowledge', requiredPermissions: ['menu:knowledge'] },
      },
      {
        path: 'settings',
        name: 'Settings',
        component: () => import('@/views/settings/index.vue'),
        meta: { title: '系统配置', icon: 'Setting', requiredPermissions: ['menu:system-config'] },
      },
      {
        path: 'profile',
        name: 'Profile',
        component: () => import('@/views/settings/profile.vue'),
        meta: { title: '个人设置', hidden: true },
      },
      {
        path: 'settings/projects',
        name: 'ProjectSettings',
        component: () => import('@/views/settings/projects.vue'),
        meta: { title: '项目管理', hidden: true, requiredPermissions: ['menu:settings:project'] },
      },
      {
        path: 'settings/users',
        name: 'UserManage',
        component: () => import('@/views/settings/users.vue'),
        meta: { title: '用户管理', hidden: true, requiredPermissions: ['menu:settings:user'] },
      },
      {
        path: 'settings/roles',
        name: 'RoleManage',
        component: () => import('@/views/settings/roles.vue'),
        meta: { title: '角色管理', hidden: true, requiredPermissions: ['menu:settings:role'] },
      },
      {
        path: 'system/workflow-config',
        name: 'WorkflowConfig',
        component: () => import('@/views/system/workflow-config/index.vue'),
        meta: { title: '工作流配置', icon: 'Share', requiredRoles: ['admin', 'workflow:config'], requiredPermissions: ['menu:settings:workflow'] },
      },
      {
        path: 'system/workflow-config/editor',
        name: 'WorkflowConfigEditor',
        component: () => import('@/views/system/workflow-config/editor.vue'),
        meta: { title: '工作流编辑器', hidden: true, activeMenu: '/system/workflow-config' },
      },
      {
        path: 'system/workflow-migration',
        name: 'WorkflowMigration',
        component: () => import('@/views/system/workflow-migration/index.vue'),
        meta: { title: '工作流迁移管理', hidden: true, activeMenu: '/system/workflow-config', requiredRoles: ['admin', 'SUPER_ADMIN'], requiredPermissions: ['admin:workflow:migration'] },
      },
      {
        path: 'settings/requirements',
        name: 'RequirementConfig',
        component: () => import('@/views/settings/requirements.vue'),
        meta: { title: '需求配置', hidden: true, requiredPermissions: ['menu:settings:requirement'] },
      },
      {
        path: 'settings/requirement-templates',
        name: 'RequirementTemplates',
        component: () => import('@/views/settings/requirement-templates/index.vue'),
        meta: { title: '需求模板', hidden: true, requiredPermissions: ['menu:settings:requirement'] },
      },
      {
        path: 'settings/menus',
        name: 'MenuManagement',
        component: () => import('@/views/settings/menus.vue'),
        meta: { title: '菜单管理', hidden: true, requiredPermissions: ['menu:menu-management'] },
      },
      {
        path: 'settings/llm',
        name: 'LlmConfig',
        component: () => import('@/views/settings/llm.vue'),
        meta: { title: '模型配置', requiredPermissions: ['menu:settings:llm'] },
      },
      {
        path: 'settings/assistant',
        name: 'AssistantSettings',
        component: () => import('@/views/settings/assistant.vue'),
        meta: { title: 'AI 助手设置', hidden: true, requiredPermissions: ['menu:system-config'] },
      },
      {
        path: 'settings/git/platforms',
        name: 'GitPlatforms',
        component: () => import('@/views/settings/git/platforms.vue'),
        meta: { title: 'Git 平台配置', hidden: true, requiredPermissions: ['menu:system-config'] },
      },
      {
        path: 'settings/git/repositories',
        name: 'GitRepositories',
        component: () => import('@/views/settings/git/repositories.vue'),
        meta: { title: '代码仓库管理', hidden: true, requiredPermissions: ['menu:system-config'] },
      },
      {
        path: 'settings/git/repositories/:id',
        name: 'GitRepositoryDetail',
        component: () => import('@/views/settings/git/repository-detail.vue'),
        meta: { title: '仓库详情', hidden: true, activeMenu: '/settings/git/repositories' },
      },
      {
        path: 'settings/git/rule-sets',
        name: 'GitRuleSets',
        component: () => import('@/views/settings/git/rule-sets.vue'),
        meta: { title: '保护规则集', hidden: true, requiredPermissions: ['menu:system-config'] },
      },
      {
        path: 'notifications',
        name: 'Notifications',
        component: () => import('@/views/notifications/index.vue'),
        meta: { title: '通知中心', hidden: true },
      },
    ],
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'NotFound',
    redirect: '/dashboard',
  },
]
