/**
 * Remix Icon 精选科技感图标数据
 * 从 2800+ 图标中精选 ~400 个科技感强的图标，按功能分为 12 个类别
 * 图标名格式: ri-{name}-line / ri-{name}-fill
 */

export interface RemixIconCategory {
  label: string
  icons: string[]
}

export const remixIconCategories: RemixIconCategory[] = [
  {
    label: 'AI / 智能',
    icons: [
      'ri-robot-line', 'ri-robot-fill', 'ri-robot-2-line', 'ri-robot-2-fill',
      'ri-brain-line', 'ri-brain-fill', 'ri-brain-2-line', 'ri-brain-2-fill',
      'ri-magic-line', 'ri-magic-fill', 'ri-sparkling-line', 'ri-sparkling-fill',
      'ri-sparkling-2-line', 'ri-sparkling-2-fill',
      'ri-chat-smile-ai-line', 'ri-chat-smile-ai-fill',
      'ri-ai-generate', 'ri-ai-generate-text',
      'ri-openai-line', 'ri-openai-fill',
      'ri-mind-map', 'ri-node-tree',
      'ri-lightbulb-line', 'ri-lightbulb-fill',
      'ri-lightbulb-flash-line', 'ri-lightbulb-flash-fill',
      'ri-flashlight-line', 'ri-flashlight-fill',
      'ri-hand-coin-line', 'ri-hand-coin-fill',
      'ri-eye-line', 'ri-eye-fill',
      'ri-eye-2-line', 'ri-eye-2-fill',
      'ri-focus-3-line', 'ri-focus-3-fill',
      'ri-compass-3-line', 'ri-compass-3-fill',
      'ri-graduation-cap-line', 'ri-graduation-cap-fill',
      'ri-microscope-line', 'ri-microscope-fill',
      'ri-flask-line', 'ri-flask-fill',
      'ri-test-tube-line', 'ri-test-tube-fill',
      'ri-dna-line', 'ri-dna-fill',
      'ri-atom-line', 'ri-atom-fill',
      'ri-infinity-line',
    ],
  },
  {
    label: '开发工具',
    icons: [
      'ri-terminal-box-line', 'ri-terminal-box-fill',
      'ri-terminal-line', 'ri-terminal-fill',
      'ri-code-box-line', 'ri-code-box-fill',
      'ri-code-line', 'ri-code-fill',
      'ri-code-s-slash-line',
      'ri-code-view',
      'ri-git-branch-line', 'ri-git-branch-fill',
      'ri-git-commit-line', 'ri-git-commit-fill',
      'ri-git-merge-line', 'ri-git-merge-fill',
      'ri-git-pull-request-line', 'ri-git-pull-request-fill',
      'ri-git-repository-line', 'ri-git-repository-fill',
      'ri-bug-line', 'ri-bug-fill',
      'ri-hammer-line', 'ri-hammer-fill',
      'ri-tools-line', 'ri-tools-fill',
      'ri-wrench-line', 'ri-wrench-fill',
      'ri-settings-3-line', 'ri-settings-3-fill',
      'ri-settings-4-line', 'ri-settings-4-fill',
      'ri-puzzle-line', 'ri-puzzle-fill',
      'ri-puzzle-2-line', 'ri-puzzle-2-fill',
      'ri-css3-line', 'ri-css3-fill',
      'ri-html5-line', 'ri-html5-fill',
      'ri-javascript-line', 'ri-javascript-fill',
      'ri-java-line', 'ri-java-fill',
      'ri-python-line', 'ri-python-fill',
      'ri-separator',
      'ri-hashtag',
      'ri-regex-line',
      'ri-braces-line',
    ],
  },
  {
    label: '数据 / 分析',
    icons: [
      'ri-bar-chart-line', 'ri-bar-chart-fill',
      'ri-bar-chart-2-line', 'ri-bar-chart-2-fill',
      'ri-bar-chart-box-line', 'ri-bar-chart-box-fill',
      'ri-bar-chart-grouped-line', 'ri-bar-chart-grouped-fill',
      'ri-bar-chart-horizontal-line',
      'ri-line-chart-line', 'ri-line-chart-fill',
      'ri-pie-chart-line', 'ri-pie-chart-fill',
      'ri-pie-chart-2-line', 'ri-pie-chart-2-fill',
      'ri-pie-chart-box-line',
      'ri-donut-chart-line', 'ri-donut-chart-fill',
      'ri-bubble-chart-line', 'ri-bubble-chart-fill',
      'ri-radar-line',
      'ri-flow-chart',
      'ri-database-2-line', 'ri-database-2-fill',
      'ri-server-line', 'ri-server-fill',
      'ri-hard-drive-2-line', 'ri-hard-drive-2-fill',
      'ri-cpu-line', 'ri-cpu-fill',
      'ri-circuit-line',
      'ri-pulse-line',
      'ri-heart-pulse-line', 'ri-heart-pulse-fill',
      'ri-funds-line', 'ri-funds-fill',
      'ri-funds-box-line', 'ri-funds-box-fill',
      'ri-stock-line', 'ri-stock-fill',
      'ri-increase-decrease-line',
      'ri-percent-line',
      'ri-timer-flash-line',
    ],
  },
  {
    label: '云 / 网络',
    icons: [
      'ri-cloud-line', 'ri-cloud-fill',
      'ri-cloud-off-line',
      'ri-cloud-upload-line', 'ri-cloud-upload-fill',
      'ri-cloud-download-line', 'ri-cloud-download-fill',
      'ri-cloud-sync-line',
      'ri-cloud-wifi-line',
      'ri-cloud-computing-line', 'ri-cloud-computing-fill',
      'ri-global-line', 'ri-global-fill',
      'ri-earth-line', 'ri-earth-fill',
      'ri-earth-globe-line',
      'ri-router-line', 'ri-router-fill',
      'ri-wifi-line', 'ri-wifi-fill',
      'ri-wifi-off-line',
      'ri-signal-wifi-line',
      'ri-signal-tower-line', 'ri-signal-tower-fill',
      'ri-broadcast-line',
      'ri-satellite-line', 'ri-satellite-fill',
      'ri-base-station-line',
      'ri-share-circle-line',
      'ri-links-line', 'ri-links-fill',
      'ri-link-source',
      'ri-rss-line',
      'ri-webhook-line',
      'ri-network-line',
      'ri-proxy-line',
      'ri-shield-keyhole-line', 'ri-shield-keyhole-fill',
    ],
  },
  {
    label: '安全 / 认证',
    icons: [
      'ri-shield-line', 'ri-shield-fill',
      'ri-shield-check-line', 'ri-shield-check-fill',
      'ri-shield-cross-line', 'ri-shield-cross-fill',
      'ri-shield-star-line', 'ri-shield-star-fill',
      'ri-shield-flash-line', 'ri-shield-flash-fill',
      'ri-shield-user-line', 'ri-shield-user-fill',
      'ri-shield-keyhole-line', 'ri-shield-keyhole-fill',
      'ri-lock-line', 'ri-lock-fill',
      'ri-lock-password-line',
      'ri-lock-2-line', 'ri-lock-2-fill',
      'ri-unlock-line', 'ri-unlock-fill',
      'ri-key-line', 'ri-key-fill',
      'ri-key-2-line', 'ri-key-2-fill',
      'ri-fingerprint-line',
      'ri-scan-line', 'ri-scan-fill',
      'ri-scan-2-line', 'ri-scan-2-fill',
      'ri-qr-code-line',
      'ri-qr-scan-2-line',
      'ri-safe-line', 'ri-safe-fill',
      'ri-passport-line',
      'ri-file-shield-line', 'ri-file-shield-fill',
      'ri-admin-line', 'ri-admin-fill',
      'ri-police-badge-line',
      'ri-spam-3-line',
      'ri-virus-line',
      'ri-fire-line', 'ri-fire-fill',
    ],
  },
  {
    label: '通信 / 消息',
    icons: [
      'ri-message-2-line', 'ri-message-2-fill',
      'ri-message-3-line', 'ri-message-3-fill',
      'ri-chat-1-line', 'ri-chat-1-fill',
      'ri-chat-2-line',
      'ri-chat-3-line', 'ri-chat-3-fill',
      'ri-chat-check-line',
      'ri-chat-new-line',
      'ri-discuss-line',
      'ri-question-answer-line',
      'ri-feedback-line',
      'ri-notification-2-line', 'ri-notification-2-fill',
      'ri-notification-3-line', 'ri-notification-3-fill',
      'ri-notification-badge-line',
      'ri-megaphone-line', 'ri-megaphone-fill',
      'ri-speaker-line', 'ri-speaker-fill',
      'ri-volume-up-line', 'ri-volume-up-fill',
      'ri-mic-line', 'ri-mic-fill',
      'ri-mic-2-line',
      'ri-headphone-line', 'ri-headphone-fill',
      'ri-customer-service-line', 'ri-customer-service-fill',
      'ri-phone-line', 'ri-phone-fill',
      'ri-video-chat-line', 'ri-video-chat-fill',
      'ri-mail-line', 'ri-mail-fill',
      'ri-mail-send-line', 'ri-mail-send-fill',
      'ri-at-line',
      'ri-chat-smile-2-line',
      'ri-emotion-happy-line', 'ri-emotion-happy-fill',
      'ri-emotion-line',
    ],
  },
  {
    label: '媒体 / 创意',
    icons: [
      'ri-camera-line', 'ri-camera-fill',
      'ri-camera-lens-line', 'ri-camera-lens-fill',
      'ri-image-line', 'ri-image-fill',
      'ri-image-2-line',
      'ri-gallery-line', 'ri-gallery-fill',
      'ri-gallery-upload-line',
      'ri-video-line', 'ri-video-fill',
      'ri-video-add-line',
      'ri-movie-2-line', 'ri-movie-2-fill',
      'ri-film-line',
      'ri-clapperboard-line',
      'ri-music-line', 'ri-music-fill',
      'ri-music-2-line', 'ri-music-2-fill',
      'ri-headphone-line',
      'ri-radio-line',
      'ri-palette-line', 'ri-palette-fill',
      'ri-paint-brush-line', 'ri-paint-brush-fill',
      'ri-quill-pen-line',
      'ri-pencil-ruler-2-line',
      'ri-crop-line',
      'ri-contrast-2-line',
      'ri-drop-line',
      'ri-screenshot-line', 'ri-screenshot-fill',
      'ri-slideshow-line', 'ri-slideshow-fill',
      'ri-presentation-line',
      'ri-vidicon-line', 'ri-vidicon-fill',
      'ri-live-line',
      'ri-webcam-line',
      'ri-dv-line',
      'ri-scissors-line', 'ri-scissors-fill',
      'ri-focus-line',
    ],
  },
  {
    label: '设备 / 硬件',
    icons: [
      'ri-computer-line', 'ri-computer-fill',
      'ri-desktop-line', 'ri-desktop-fill',
      'ri-laptop-line', 'ri-laptop-fill',
      'ri-tablet-line', 'ri-tablet-fill',
      'ri-smartphone-line', 'ri-smartphone-fill',
      'ri-phone-line', 'ri-phone-fill',
      'ri-watch-line',
      'ri-tv-line', 'ri-tv-fill',
      'ri-router-line', 'ri-router-fill',
      'ri-printer-line', 'ri-printer-fill',
      'ri-scanner-line', 'ri-scanner-fill',
      'ri-keyboard-line', 'ri-keyboard-fill',
      'ri-keyboard-box-line', 'ri-keyboard-box-fill',
      'ri-mouse-line', 'ri-mouse-fill',
      'ri-usb-line',
      'ri-bluetooth-line', 'ri-bluetooth-fill',
      'ri-battery-line',
      'ri-charging-pile-line', 'ri-charging-pile-fill',
      'ri-cpu-line', 'ri-cpu-fill',
      'ri-hard-drive-line', 'ri-hard-drive-fill',
      'ri-hard-drive-2-line', 'ri-hard-drive-2-fill',
      'ri-server-line', 'ri-server-fill',
      'ri-database-line', 'ri-database-fill',
      'ri-sensor-line',
      'ri-remote-control-line', 'ri-remote-control-fill',
      'ri-ram-line', 'ri-ram-fill',
      'ri-disc-line', 'ri-disc-fill',
    ],
  },
  {
    label: '商务 / 办公',
    icons: [
      'ri-briefcase-line', 'ri-briefcase-fill',
      'ri-briefcase-2-line', 'ri-briefcase-2-fill',
      'ri-briefcase-3-line', 'ri-briefcase-3-fill',
      'ri-briefcase-4-line', 'ri-briefcase-4-fill',
      'ri-building-line', 'ri-building-fill',
      'ri-building-2-line', 'ri-building-2-fill',
      'ri-building-4-line', 'ri-building-4-fill',
      'ri-home-office-line',
      'ri-team-line',
      'ri-user-line', 'ri-user-fill',
      'ri-user-star-line', 'ri-user-star-fill',
      'ri-user-settings-line',
      'ri-user-add-line',
      'ri-user-search-line',
      'ri-group-line',
      'ri-contacts-line',
      'ri-profile-line',
      'ri-id-card-line', 'ri-id-card-fill',
      'ri-stamp-line',
      'ri-calendar-todo-line',
      'ri-calendar-check-line',
      'ri-task-line', 'ri-task-fill',
      'ri-todo-line', 'ri-todo-fill',
      'ri-trophy-line', 'ri-trophy-fill',
      'ri-award-line',
      'ri-medal-line',
      'ri-flag-line', 'ri-flag-fill',
      'ri-target-line',
      'ri-focus-2-line',
      'ri-cursor-line',
      'ri-dashboard-line', 'ri-dashboard-fill',
      'ri-bar-chart-box-line',
      'ri-file-chart-line',
    ],
  },
  {
    label: '设计 / 界面',
    icons: [
      'ri-layout-line', 'ri-layout-fill',
      'ri-layout-2-line', 'ri-layout-2-fill',
      'ri-layout-3-line', 'ri-layout-3-fill',
      'ri-layout-4-line', 'ri-layout-4-fill',
      'ri-layout-5-line', 'ri-layout-5-fill',
      'ri-layout-6-line', 'ri-layout-6-fill',
      'ri-layout-grid-line', 'ri-layout-grid-fill',
      'ri-layout-masonry-line',
      'ri-grid-line', 'ri-grid-fill',
      'ri-apps-line', 'ri-apps-fill',
      'ri-apps-2-line',
      'ri-menu-line', 'ri-menu-fill',
      'ri-menu-2-line',
      'ri-menu-3-line',
      'ri-menu-4-line',
      'ri-menu-5-line',
      'ri-navigation-line',
      'ri-side-bar-line', 'ri-side-bar-fill',
      'ri-drag-move-line',
      'ri-drag-drop-line',
      'ri-fullscreen-line', 'ri-fullscreen-fill',
      'ri-aspect-ratio-line',
      'ri-artboard-line', 'ri-artboard-fill',
      'ri-shape-line', 'ri-shape-fill',
      'ri-shape-2-line',
      'ri-pentagon-line',
      'ri-hexagon-line',
      'ri-octagon-line',
      'ri-triangle-line',
      'ri-ruler-line', 'ri-ruler-fill',
      'ri-ruler-2-line',
      'ri-screenshot-line',
      'ri-eye-off-line',
    ],
  },
  {
    label: '箭头 / 方向',
    icons: [
      'ri-arrow-up-line', 'ri-arrow-up-fill',
      'ri-arrow-down-line', 'ri-arrow-down-fill',
      'ri-arrow-left-line', 'ri-arrow-left-fill',
      'ri-arrow-right-line', 'ri-arrow-right-fill',
      'ri-arrow-up-circle-line', 'ri-arrow-up-circle-fill',
      'ri-arrow-down-circle-line', 'ri-arrow-down-circle-fill',
      'ri-arrow-left-circle-line', 'ri-arrow-left-circle-fill',
      'ri-arrow-right-circle-line', 'ri-arrow-right-circle-fill',
      'ri-arrow-up-double-line',
      'ri-arrow-right-double-line',
      'ri-arrow-left-right-line',
      'ri-arrow-up-down-line',
      'ri-corner-up-left-line', 'ri-corner-up-right-line',
      'ri-corner-down-left-line', 'ri-corner-down-right-line',
      'ri-corner-left-up-line', 'ri-corner-right-up-line',
      'ri-expand-left-line', 'ri-expand-right-line',
      'ri-expand-up-down-line',
      'ri-collapse-all-line',
      'ri-contract-left-right-line',
      'ri-contract-up-down-line',
      'ri-expand-diagonal-line',
      'ri-external-link-line',
      'ri-refresh-line', 'ri-refresh-fill',
      'ri-loop-left-line', 'ri-loop-right-line',
      'ri-round-line',
      'ri-anticlockwise-line', 'ri-anticlockwise-fill',
      'ri-clockwise-line', 'ri-clockwise-fill',
      'ri-skip-forward-line',
      'ri-skip-back-line',
    ],
  },
  {
    label: '系统 / 状态',
    icons: [
      'ri-check-line', 'ri-check-fill',
      'ri-check-double-line',
      'ri-close-line', 'ri-close-fill',
      'ri-close-circle-line', 'ri-close-circle-fill',
      'ri-add-line', 'ri-add-fill',
      'ri-add-circle-line', 'ri-add-circle-fill',
      'ri-subtract-line',
      'ri-subtract-line',
      'ri-forbid-line', 'ri-forbid-fill',
      'ri-information-line', 'ri-information-fill',
      'ri-error-warning-line', 'ri-error-warning-fill',
      'ri-alert-line', 'ri-alert-fill',
      'ri-alarm-warning-line',
      'ri-checkbox-circle-line', 'ri-checkbox-circle-fill',
      'ri-close-circle-line', 'ri-close-circle-fill',
      'ri-indeterminate-circle-line',
      'ri-question-line', 'ri-question-fill',
      'ri-more-line', 'ri-more-fill',
      'ri-more-2-line', 'ri-more-2-fill',
      'ri-equal-line',
      'ri-separator',
      'ri-loading-3-line', 'ri-loader-2-line',
      'ri-spam-line', 'ri-spam-fill',
      'ri-fire-line', 'ri-fire-fill',
      'ri-zap-line', 'ri-zap-fill',
      'ri-thunderstorms-line',
      'ri-stop-circle-line', 'ri-stop-circle-fill',
      'ri-power-line',
      'ri-signal-wifi-error-line',
    ],
  },
]

/** 判断图标名是否为 Remix Icon */
export function isRemixIcon(name: string): boolean {
  return name.startsWith('ri-')
}

/** 获取所有 Remix Icon 图标名 */
export function getAllRemixIconNames(): string[] {
  const names: string[] = []
  remixIconCategories.forEach(c => c.icons.forEach(i => names.push(i)))
  return names
}

/** 搜索 Remix Icon 图标 */
export function searchRemixIcons(keyword: string): string[] {
  if (!keyword.trim()) return getAllRemixIconNames()
  const lower = keyword.toLowerCase()
  return getAllRemixIconNames().filter(name => name.toLowerCase().includes(lower))
}
